stages:
  - build
  - publish
  - test

variables:
  DOCKER_HOST: tcp://host.docker.internal:2375
  DOCKER_DRIVER: overlay2
  REGISTRY_URL: "192.168.1.204:5000" # Укажите адрес вашего Docker Registry
  IMAGE_NAME: "${REGISTRY_URL}/my-shops"

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Building the Docker image..."
    - docker build -t $IMAGE_NAME .
    - docker tag $IMAGE_NAME $IMAGE_NAME:latest
  only:
    - master

publish:
  stage: publish
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Pushing the Docker image to the registry..."
    - docker push $IMAGE_NAME
  only:
    - master

test:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Installing curl..."
    - apk add --no-cache curl
    - echo "Docker run image"
    - docker run -d -p 8080:80 --name test_container $IMAGE_NAME
    - echo "Waiting for the container to start..."
    - sleep 20
    - echo "Testing the application..."
    - docker exec -it test_container curl  http://localhost:80 || (echo "Test failed"; exit 1)
    - echo "Test passed!"
    - docker stop test_container
    - docker rm test_container
  only:
    - master
