stages:
  - build
  - test

build:
  stage: build
  image: docker:latest
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "Building the Docker image..."
    - docker build -t my-shops .
  only:
    - master

test:
  stage: test
  script:
    - echo "Running tests in Docker container..."
    - docker run --rm my-shops .
