stages:
  - build
  - test

build:
  stage: build
  image: node:latest
  services:
    - name: docker:dind
      command: ["--privileged"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "Current directory:$(pwd)"
    - echo "Contents of the directory:"
    - ls -la
    - echo "Cloning the repository..."
    - echo "Cleaning up existing files..."
    - find . -mindepth 1 -delete
    - rm -rf ./*           # Удалить все файлы в текущей директории
    - rm -rf ./.git        # Удалить папку .git, если она существует
    - git config --global credential.helper store
    - echo "http://${GITLAB_USER}:${GITLAB_PASSWORD}@192.168.1.204:8080/maksdev/shops.git" > ~/.git-credentials
    - git clone http://${GITLAB_USER}:${GITLAB_PASSWORD}@192.168.1.204:8080/maksdev/shops.git .
    - echo "Building the Docker image..."
    - docker build -t my-app .
  only:
    - master

test:
  stage: test
  script:
    - echo "Running tests in Docker container..."
    - docker run --rm my-shops .
