stages:
  - build
  - publish
  - test

variables:
  DOCKER_HOST: tcp://host.docker.internal:2375
  DOCKER_DRIVER: overlay2
  REGISTRY_URL: "192.168.1.204:5000" # Укажите адрес вашего Docker Registry
  IMAGE_NAME: "${REGISTRY_URL}/my-shops"
  IMAGE_Del: "my-shops"
  REGISTRY_URL_V2: http://localhost:5000
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Building the Docker image..."
    - docker build -t $IMAGE_NAME .
    - docker tag $IMAGE_NAME $IMAGE_NAME:latest
  only:
    - master

publish:
  stage: publish
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Pushing the Docker image to the registry..."
    - docker push $IMAGE_NAME
  only:
    - master

test1:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Installing curl..."
    - apk add --no-cache curl
    - echo "Docker run image"
    - docker run -d -p 8080:80 --name test_container $IMAGE_NAME
    - echo "Waiting for the container to start..."
    - sleep 20
    - echo "Testing the application..."
    - docker exec test_container curl  http://localhost:80 || (echo "Test failed"; exit 1)
    - echo "Test passed!"
    - docker stop test_container
    - docker rm test_container
  only:
    - master
build_category:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Building the Docker image..."
    - docker build -t ${IMAGE_NAME}category -f Dockerfile_Category .
    - docker tag ${IMAGE_NAME}category ${IMAGE_NAME}category:latest
  only:
    - master
publish_category:
  stage: publish
  image: docker:latest
  services:
    - docker:dind
  script:
    # Установим curl
    - apk add --no-cache curl
    # Удаление старого образа, если он существует
    - echo "Checking and deleting the existing Docker image..."
    - |
      DIGEST=$(curl -sI -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
        ${REGISTRY_URL_V2}/v2/${IMAGE_Del}category/manifests/latest | \
        grep Docker-Content-Digest | awk '{print $2}' | tr -d '\r')
      
      if [ -n "$DIGEST" ]; then
        echo "Old image found. Deleting ${IMAGE_Del}category with digest $DIGEST..."
        curl -s -X DELETE ${REGISTRY_URL_V2}/v2/${IMAGE_Del}category/manifests/$DIGEST
        echo "Old image deleted successfully."
      else
        echo "No existing image found. Skipping deletion."
      fi
    # Публикация нового образа
    - echo "Building and pushing the new Docker image to the registry..."
    - docker build -t ${IMAGE_NAME}category .
    - docker push ${IMAGE_NAME}category
  only:
    - master
    
test2_category:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Installing curl..."
    - apk add --no-cache curl
    - echo "Docker run image"
    - docker-compose -f dockercategor.yml up -d
    - echo "Waiting for the container to start..."
    - sleep 30
    - echo "Testing the application..."
    - docker exec category-service curl  http://localhost:80 || (echo "Test failed"; exit 1)
    - echo "Test passed!"
    - docker-compose -f dockercategor.yml down
  only:
    - master



