stages:
  - build
  - test

build:
  stage: build
  script:
    - git config --global credential.helper store
    - echo "http://${GITLAB_USER}:${GITLAB_PASSWORD}@192.168.1.204/maksdev/shops.git" > ~/.git-credentials
    - git pull
    - echo "Building project..."

test:
  stage: test
  script:
    - echo "Running tests in Docker container..."
    - docker run --rm my-app ./run-tests.sh