stages:
  - build
  - publish
  - test

variables:
  DOCKER_HOST: tcp://host.docker.internal:2375
  DOCKER_DRIVER: overlay2
  REGISTRY_URL: "192.168.1.204:5000" # Укажите адрес вашего Docker Registry
  IMAGE_NAME: "${REGISTRY_URL}/my-shops"

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Building the Docker image..."
    - docker build -t $IMAGE_NAME .
    - docker tag $IMAGE_NAME $IMAGE_NAME:latest
  only:
    - master

publish:
  stage: publish
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Pushing the Docker image to the registry..."
    - docker push $IMAGE_NAME
  only:
    - master

test:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Docker run image"
    - docker run -p 8080:80  $IMAGE_NAME
  only:
    - master
