version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"      # Jenkins Web UI
      - "50000:50000"    # Jenkins agents
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    restart: always

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: gitlab.local
    ports:
      - "8929:8929"      # Web UI of GitLab
      - "2222:22"        # SSH for GitLab
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.1.204:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    restart: always

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    depends_on:
      - gitlab
    volumes:
      - gitlab_runner_config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock  # Для Docker Executor
    environment:
      - CI_SERVER_URL=http://192.168.1.204:8929  # Сетевой адрес GitLab
    restart: always

volumes:
  jenkins_home:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  gitlab_runner_config:
