version: '3.9'

networks:
  gitlab_network:
    driver: bridge

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"      # Jenkins Web UI
      - "50000:50000"    # Jenkins agents
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    restart: always
    networks:
      - gitlab_network

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: gitlab.local
    ports:
      - "8929:8929"      # Web UI of GitLab
      - "2222:22"        # SSH for GitLab
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        registry['enable'] = true
        registry_external_url 'http://docker-registry:5000'
        gitlab_rails['registry_host'] = 'docker-registry'
        gitlab_rails['registry_port'] = '5000'
    restart: always
    networks:
      - gitlab_network

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    depends_on:
      - gitlab
    volumes:
      - gitlab_runner_config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock  # Для Docker Executor
    environment:
      - CI_SERVER_URL=http://gitlab:8929  # Внутренний DNS GitLab в сети
    restart: always
    networks:
      - gitlab_network

  docker-registry:
    image: registry:2
    container_name: docker-registry
    ports:
      - "5000:5000"      # Docker Registry port
    volumes:
      - registry_data:/var/lib/registry
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
    restart: always
    networks:
      - gitlab_network

volumes:
  jenkins_home:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  gitlab_runner_config:
  registry_data:
